### ISSUE TITLE
Can't update cover image for a game

### ISSUE THREAD

**Issue by JCBoorgo** [cjs8487/bingogg#25]
I've tried with Balatro, and when I try to save changes I get a toast notification saying that no changes were made, and so it doesn't save. The image I've provided in the first place doesn't work either, don't know if that's a bug or something I don't know about how the images should be or whatever. If possible, change to this please https://cdn2.steamgriddb.com/logo_thumb/fab4029f3293f283d3e94873e7ea7db2.png
kthx

**Comment by JCBoorgo** [comment]
Looks like I'm also unable to create a room, is there something more broken with the website that I'm unaware of?

**Comment by cjs8487** [comment]
This should be permanently fixed as of the the latest commit
